<?php

namespace Modules\Finance\Policies;

use Modules\Core\Entities\User;
use Modules\Finance\Entities\Invoice;
use Illuminate\Auth\Access\HandlesAuthorization;

class InvoicePolicy
{
    use HandlesAuthorization;

    public function viewAny(User $user)
    {
        return $user->can('view-finance');
    }

    public function view(User $user, Invoice $invoice)
    {
        if ($user->can('view-finance')) {
            return true;
        }

        if ($user->hasRole('parent') && $invoice->student->parents->contains($user->id)) {
            return true;
        }

        if ($user->hasRole('student') && $invoice->student->user_id === $user->id) {
            return true;
        }

        return false;
    }

    public function create(User $user)
    {
        return $user->can('manage-payments'); // invoices usually generated by system or admin
    }

    public function update(User $user, Invoice $invoice)
    {
        return $user->can('manage-payments');
    }

    public function delete(User $user, Invoice $invoice)
    {
        return $user->can('manage-payments');
    }
}
